services:
  crm-service:
    platform: linux/amd64
    build: ../backend
    image: crm/backend
    container_name: crm
    depends_on:
      - postgres
    ports:
      - "5588:8080"
    env_file: ../../env_files/crm.env
    environment:
      CONFIG_ENV: ${PROFILE_ARG}
      POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGODB_URI: mongodb://mongo:27017/crm
    networks:
      - backend

  postgres:
    image: docker.io/library/postgres:16.6
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: ../../env_files/crm.env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    networks:
      - backend
      
  mongo:
    image: docker.io/library/mongo:8.0.10
    container_name: mongo
    ports:
      - "27017:27017"
    env_file: ../../env_files/crm.env
    environment:
      MONGO_INITDB_DATABASE: crm
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
      - backend

networks:
  backend: { }